apiVersion: v1
kind: PersistentVolume
metadata:
  name: codesys-conf-pv
  namespace: {{ .Values.namespace }}
spec:
  capacity:
    storage: {{ .Values.pv.conf.storage }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.pv.conf.hostPath }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: codesys-data-pv
  namespace: {{ .Values.namespace }}
spec:
  capacity:
    storage: {{ .Values.pv.data.storage }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.pv.data.hostPath }}
