apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: codesys-conf-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pv.conf.storage }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: codesys-data-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pv.data.storage }}
