namespace: "codesys"

# PersistentVolume configuration
pv:
  conf:
    storage: "1Gi"
    hostPath: "/mnt/data/codesys/conf"
  data:
    storage: "10Gi"
    hostPath: "/mnt/data/codesys/data"

# Deployment Configuration
deployment:
  replicas: 1
  nodeSelector:
    vplc: "true"  # Ensure it only runs on nodes with label 'vplc=true'

# Codesys edge gateway container configuration
codesysEdgeGateway:
  image: "gsmartcodesys/codesysedge_edgeamd64"
  containerPort: 1217

# Codesys virtual control container configuration
codesysVirtualControl:
  image: "runtimevictor/codesyscontrol_virtuallinux:v1.0.0"
  containerPorts:
    - name: codesys-service
      port: 11740
    - name: opc-ua
      port: 4840
    - name: http
      port: 8080
    - name: https
      port: 443
    - name: mqtt
      port: 1883
    - name: secure-mqtt
      port: 8883

# Service configuration
service:
  name: "codesys-service"
  loadBalancerIP: "192.168.168.103"
  ports:
    - name: codesys-service
      port: 11740
      targetPort: 11740
    - name: opc-ua
      port: 4840
      targetPort: 4840
    - name: http
      port: 8080
      targetPort: 8080
    - name: https
      port: 443
      targetPort: 443
    - name: mqtt
      port: 1883
      targetPort: 1883
    - name: secure-mqtt
      port: 8883
      targetPort: 8883
    - name: gateway
      port: 1217
      targetPort: 1217
